public class XbnfParser : Pck.Lalr1TableParser {
    public const int grammar = 0;
    public const int productions = 1;
    public const int production = 2;
    public const int expressions = 3;
    public const int expression = 4;
    public const int symbol = 5;
    public const int attributes = 6;
    public const int attribute = 7;
    public const int attrvalue = 8;
    public const int expressionlisttail = 9;
    public const int symbollist = 10;
    public const int attributelisttail = 11;
    public const int identifier = 12;
    public const int lt = 13;
    public const int gt = 14;
    public const int eq = 15;
    public const int semi = 16;
    public const int literal = 17;
    public const int regex = 18;
    public const int lparen = 19;
    public const int rparen = 20;
    public const int lbracket = 21;
    public const int rbracket = 22;
    public const int lbrace = 23;
    public const int rbrace = 24;
    public const int rbracePlus = 25;
    public const int integer = 26;
    public const int or = 27;
    public const int comma = 28;
    public const int whitespace = 29;
    public const int lineComment = 30;
    public const int blockComment = 31;
    public const int _EOS = 32;
    public const int _ERROR = 33;
    static string[] _Symbols = new string[] {
            "grammar",
            "productions",
            "production",
            "expressions",
            "expression",
            "symbol",
            "attributes",
            "attribute",
            "attrvalue",
            "expressionlisttail",
            "symbollist",
            "attributelisttail",
            "identifier",
            "lt",
            "gt",
            "eq",
            "semi",
            "literal",
            "regex",
            "lparen",
            "rparen",
            "lbracket",
            "rbracket",
            "lbrace",
            "rbrace",
            "rbracePlus",
            "integer",
            "or",
            "comma",
            "whitespace",
            "lineComment",
            "blockComment",
            "#EOS",
            "#ERROR"};
    static int[][][] _ParseTable = new int[][][] {
            new int[][] {
                    new int[] {
                            1},
                    new int[] {
                            2},
                    new int[] {
                            3},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            5},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            -1}},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            0,
                            0,
                            1}},
            new int[][] {
                    null,
                    new int[] {
                            4},
                    new int[] {
                            3},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            5},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            2,
                            1,
                            2}},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            1,
                            1,
                            2,
                            1}},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            6},
                    null,
                    new int[] {
                            46},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            7},
                    new int[] {
                            34},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            38},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            8},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            9},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    new int[] {
                            10},
                    new int[] {
                            12},
                    new int[] {
                            24},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16},
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    null,
                    new int[] {
                            25},
                    null,
                    new int[] {
                            28},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            11},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            3,
                            2,
                            12,
                            13,
                            6,
                            14,
                            15,
                            3,
                            16},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            3,
                            2,
                            12,
                            13,
                            6,
                            14,
                            15,
                            3,
                            16}},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            13},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            6,
                            3,
                            4},
                    null,
                    null,
                    null,
                    new int[] {
                            6,
                            3,
                            4},
                    null,
                    new int[] {
                            6,
                            3,
                            4},
                    null,
                    new int[] {
                            6,
                            3,
                            4},
                    new int[] {
                            6,
                            3,
                            4},
                    null,
                    new int[] {
                            32},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            5,
                            3,
                            4,
                            9},
                    null,
                    null,
                    null,
                    new int[] {
                            5,
                            3,
                            4,
                            9},
                    null,
                    new int[] {
                            5,
                            3,
                            4,
                            9},
                    null,
                    new int[] {
                            5,
                            3,
                            4,
                            9},
                    new int[] {
                            5,
                            3,
                            4,
                            9},
                    null,
                    new int[] {
                            14},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            15},
                    new int[] {
                            24},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16},
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    null,
                    new int[] {
                            25},
                    null,
                    new int[] {
                            28},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            23,
                            9,
                            9,
                            27,
                            4},
                    null,
                    null,
                    null,
                    new int[] {
                            23,
                            9,
                            9,
                            27,
                            4},
                    null,
                    new int[] {
                            23,
                            9,
                            9,
                            27,
                            4},
                    null,
                    new int[] {
                            23,
                            9,
                            9,
                            27,
                            4},
                    new int[] {
                            23,
                            9,
                            9,
                            27,
                            4},
                    null,
                    new int[] {
                            23,
                            9,
                            9,
                            27,
                            4},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            17},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    new int[] {
                            7,
                            4,
                            10},
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    new int[] {
                            7,
                            4,
                            10},
                    new int[] {
                            25},
                    new int[] {
                            7,
                            4,
                            10},
                    new int[] {
                            28},
                    new int[] {
                            7,
                            4,
                            10},
                    new int[] {
                            7,
                            4,
                            10},
                    null,
                    new int[] {
                            7,
                            4,
                            10},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    null,
                    null,
                    null,
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    null,
                    new int[] {
                            25,
                            10,
                            10,
                            5},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            9,
                            5,
                            17},
                    null,
                    null,
                    null,
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    new int[] {
                            9,
                            5,
                            17},
                    null,
                    new int[] {
                            9,
                            5,
                            17},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            10,
                            5,
                            18},
                    null,
                    null,
                    null,
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    new int[] {
                            10,
                            5,
                            18},
                    null,
                    new int[] {
                            10,
                            5,
                            18},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            11,
                            5,
                            12},
                    null,
                    null,
                    null,
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    new int[] {
                            11,
                            5,
                            12},
                    null,
                    new int[] {
                            11,
                            5,
                            12},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    new int[] {
                            22},
                    new int[] {
                            12},
                    new int[] {
                            24},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16},
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    null,
                    new int[] {
                            25},
                    null,
                    new int[] {
                            28},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            23},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    null,
                    null,
                    null,
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    null,
                    new int[] {
                            12,
                            5,
                            19,
                            3,
                            20},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            26,
                            10,
                            5},
                    null,
                    null,
                    null,
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    new int[] {
                            26,
                            10,
                            5},
                    null,
                    new int[] {
                            26,
                            10,
                            5},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    new int[] {
                            26},
                    new int[] {
                            12},
                    new int[] {
                            24},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16},
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    null,
                    new int[] {
                            25},
                    null,
                    new int[] {
                            28},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            27},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    null,
                    null,
                    null,
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    null,
                    new int[] {
                            13,
                            5,
                            21,
                            3,
                            22},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    new int[] {
                            29},
                    new int[] {
                            12},
                    new int[] {
                            24},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16},
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    null,
                    new int[] {
                            25},
                    null,
                    new int[] {
                            28},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            30},
                    new int[] {
                            31},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    null,
                    null,
                    null,
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    null,
                    new int[] {
                            14,
                            5,
                            23,
                            3,
                            24},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    null,
                    null,
                    null,
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    null,
                    new int[] {
                            15,
                            5,
                            23,
                            3,
                            25},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            33},
                    new int[] {
                            24},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16},
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    null,
                    new int[] {
                            25},
                    null,
                    new int[] {
                            28},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            24,
                            9,
                            27,
                            4},
                    null,
                    null,
                    null,
                    new int[] {
                            24,
                            9,
                            27,
                            4},
                    null,
                    new int[] {
                            24,
                            9,
                            27,
                            4},
                    null,
                    new int[] {
                            24,
                            9,
                            27,
                            4},
                    new int[] {
                            24,
                            9,
                            27,
                            4},
                    null,
                    new int[] {
                            24,
                            9,
                            27,
                            4},
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            35},
                    null,
                    null,
                    new int[] {
                            17,
                            6,
                            7},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            44},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16,
                            6,
                            7,
                            11},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            36},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            37},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            38},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            27,
                            11,
                            11,
                            28,
                            7},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            27,
                            11,
                            11,
                            28,
                            7},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            19,
                            7,
                            12},
                    new int[] {
                            39},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            19,
                            7,
                            12},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            40},
                    null,
                    null,
                    null,
                    new int[] {
                            43},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            41},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            42},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18,
                            7,
                            12,
                            15,
                            8},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18,
                            7,
                            12,
                            15,
                            8},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            20,
                            8,
                            17},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            20,
                            8,
                            17},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            21,
                            8,
                            26},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            21,
                            8,
                            26},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            22,
                            8,
                            12},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            22,
                            8,
                            12},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            45},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            38},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            28,
                            11,
                            28,
                            7},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            28,
                            11,
                            28,
                            7},
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    new int[] {
                            47},
                    new int[] {
                            12},
                    new int[] {
                            24},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            16},
                    null,
                    new int[] {
                            20},
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            18},
                    new int[] {
                            19},
                    new int[] {
                            21},
                    null,
                    new int[] {
                            25},
                    null,
                    new int[] {
                            28},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            48},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null},
            new int[][] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            4,
                            2,
                            12,
                            15,
                            3,
                            16},
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    new int[] {
                            4,
                            2,
                            12,
                            15,
                            3,
                            16}}};
    static int[] _NodeFlags = new int[] {
            0,
            1,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            2,
            2,
            2,
            0,
            0};
    static int[] _Substitutions = new int[] {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1};
    static System.Collections.Generic.KeyValuePair<string, object>[][] _AttributeSets = new System.Collections.Generic.KeyValuePair<string, object>[][] {
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("start", true)},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
            null,
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
            null,
            null,
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("color", "red")},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("color", "orange")},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("hidden", true),
                    new System.Collections.Generic.KeyValuePair<string, object>("terminal", true)},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("hidden", true),
                    new System.Collections.Generic.KeyValuePair<string, object>("color", "green")},
            new System.Collections.Generic.KeyValuePair<string, object>[] {
                    new System.Collections.Generic.KeyValuePair<string, object>("hidden", true),
                    new System.Collections.Generic.KeyValuePair<string, object>("blockEnd", "*/"),
                    new System.Collections.Generic.KeyValuePair<string, object>("color", "green")},
            null,
            null};
    public XbnfParser(System.Collections.Generic.IEnumerable<Pck.Token> tokenizer) : 
            base(XbnfParser._ParseTable, XbnfParser._Symbols, XbnfParser._NodeFlags, XbnfParser._Substitutions, XbnfParser._AttributeSets, tokenizer) {
    }
    public XbnfParser() : 
            this(null) {
    }
}
